# Generated by Django 5.1.7 on 2025-04-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkincareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('benefits', models.TextField(max_length=500)),
                ('value', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
