# Generated by Django 5.1.7 on 2025-04-02 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_skincareproduct_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skincareproduct',
            old_name='product',
            new_name='name',
        ),
    ]
